export const PERMISSIONS = {
  ADMINISTRATOR: 1 << 0,
  VIEW_CHANNELS: 1 << 1,
  MANAGE_CHANNELS: 1 << 2,
  MANAGE_ROLES: 1 << 3,
  MANAGE_SERVER: 1 << 4,
  VIEW_AUDIT_LOG: 1 << 5,
  SEND_MESSAGES: 1 << 6,
  READ_HISTORY: 1 << 7,
  MANAGE_MESSAGES: 1 << 8,
  ATTACH_FILES: 1 << 9,
  VOICE_CONNECT: 1 << 10,
  VOICE_SPEAK: 1 << 11,
  VOICE_MUTE_MEMBERS: 1 << 12,
  VOICE_DEAFEN_MEMBERS: 1 << 13,
  VOICE_MOVE_MEMBERS: 1 << 14,
  SCREENSHARE: 1 << 15,
  KICK_MEMBERS: 1 << 16,
  BAN_MEMBERS: 1 << 17,
  TIMEOUT_MEMBERS: 1 << 18
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS).reduce((mask, value) => mask | value, 0);

export const DEFAULT_EVERYONE_PERMS =
  PERMISSIONS.VIEW_CHANNELS |
  PERMISSIONS.SEND_MESSAGES |
  PERMISSIONS.READ_HISTORY |
  PERMISSIONS.ATTACH_FILES |
  PERMISSIONS.VOICE_CONNECT |
  PERMISSIONS.VOICE_SPEAK |
  PERMISSIONS.SCREENSHARE;

export const TIMEOUT_BLOCKED =
  PERMISSIONS.SEND_MESSAGES |
  PERMISSIONS.ATTACH_FILES |
  PERMISSIONS.VOICE_SPEAK |
  PERMISSIONS.SCREENSHARE;
